name: $(Year:yy)$(DayOfYear).$(Rev:r)
trigger:
  - master
pr: none
resources:
  repositories:
    - repository: templates
      type: github
      endpoint: shared-github
      name: audaciaconsulting/Audacia.Build

pool:
  vmImage: windows-latest

variables:
  - group: Audacia.Libraries.Dependency-Track

  # Secrets / env
  - name: DT_API_KEY
    value: $(DT-API-KEY)
  - name: DT_API_URL
    value: $(DT-API-URL)

  # Template-parameter variables
  - name: systemName
    value: Audacia.Mail.Libraries
  - name: deactivateOld
    value: true

  # Optional parent project
  - name: parentProjectName
    value: 'Audacia.Mail - Libraries'
  - name: parentProjectVersion
    value: ''

  # Project paths and settings
  - name: audaciaMailProjectPaths
    value: |
      $(System.DefaultWorkingDirectory)/Audacia.Mail/Audacia.Mail.csproj
      $(System.DefaultWorkingDirectory)/Audacia.Mail.Local/Audacia.Mail.Local.csproj
      $(System.DefaultWorkingDirectory)/Audacia.Mail.Log/Audacia.Mail.Log.csproj      
      $(System.DefaultWorkingDirectory)/Audacia.Mail.MailKit/Audacia.Mail.MailKit.csproj      
      $(System.DefaultWorkingDirectory)/Audacia.Mail.MailTrap/Audacia.Mail.MailTrap.csproj      
      $(System.DefaultWorkingDirectory)/Audacia.Mail.Mandrill/Audacia.Mail.Mandrill.csproj      
      $(System.DefaultWorkingDirectory)/Audacia.Mail.Noop/Audacia.Mail.Noop.csproj      
      $(System.DefaultWorkingDirectory)/Audacia.Mail.SendGrid/Audacia.Mail.SendGrid.csproj      
      $(System.DefaultWorkingDirectory)/Audacia.Mail.Test.API/Audacia.Mail.Test.API.csproj      
      $(System.DefaultWorkingDirectory)/Audacia.Mail.Test.App/Audacia.Mail.Test.App.csproj      

  - name: artifactName
    value: 'sbom-files'
  - name: publishArtifact
    value: true
  - name: failOnUploadError
    value: true
  - name: tryDownloadArtifact
    value: true
  - name: vstsFeed
    value: 'Audacia.Public/AudaciaPublic'

stages:
  # =========================
  # 1) GENERATE STAGE
  # =========================
  - stage: generate
    displayName: "Generate SBOMs (.NET via CycloneDX)"
    jobs:
      - job: generate_sbom
        displayName: "Generate SBOMs & publish artifact"
        steps:
          # Generate .NET SBOMs
          - template: /src/security/dependency-track/steps/generate-dotnet-sbom.steps.yaml@templates
            parameters:
              dotnetProjects: $(audaciaMailProjectPaths)
              vstsFeed: ${{ variables.vstsFeed }}
              publishArtifact: ${{ variables.publishArtifact }}
              artifactName: $(artifactName)

  # =========================
  # 2) UPLOAD STAGE
  # =========================
  - stage: upload
    displayName: "Upload SBOMs to Dependency-Track"
    dependsOn: generate
    jobs:
      - job: upload_sbom
        displayName: "Upload SBOM & Log Summary"
        steps:
          - checkout: none
          - template: /src/security/dependency-track/steps/upload-sbom.steps.yaml@templates
            parameters:
              systemName: $(systemName)
              failOnUploadError: ${{ variables.failOnUploadError }}
              parentProjectName: ${{ variables.parentProjectName }}
              parentProjectVersion: ${{ variables.parentProjectVersion }}

  # =========================
  # 3) DEACTIVATE STAGE (run standalone or after upload)
  # =========================
  - stage: deactivate
    displayName: "Deactivate old Dependency-Track project versions"
    dependsOn: upload
    condition: and(succeeded('upload'), eq(variables['deactivateOld'], true))
    jobs:
      - job: deactivate_old_versions
        displayName: "Set non-latest versions to inactive"
        steps:
          - checkout: none
          - template: /src/security/dependency-track/steps/deactivate-nonlatest.steps.yaml@templates
            parameters:
              artifactName: $(artifactName)
              tryDownloadArtifact: ${{ variables.tryDownloadArtifact }}
              parentProjectName: ${{ variables.parentProjectName }}
